baseURL = '/'
languageCode = 'en-us'
title = 'Victor Van Gestel â€“ Developer'

[params]
  name = 'Victor Van Gestel'
  role = 'Developer'
  description = 'Portfolio of Victor Van Gestel, a digital product designer focused on accessible, user-centered interfaces.'
  accentColor = '#4F46E5'

[outputs]
  home = ['HTML']
  section = ['HTML']
  page = ['HTML']

[permalinks]
  experience = '/experience/:slug/'
  studies = '/studies/:slug/'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1

  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 2

  [[menu.main]]
    identifier = 'experience'
    name = 'Experience'
    url = '/experience/'
    weight = 3

  [[menu.main]]
    identifier = 'studies'
    name = 'Studies'
    url = '/studies/'
    weight = 4

  [[menu.main]]
    identifier = 'contact'
    name = 'Contact'
    url = '/contact/'
    weight = 5

[caches]
  [caches.images]
    dir = ':cacheDir/images'